"""Leitura de transcript de sessão de agente, normalizada entre harnesses.

Somente leitura. Nada aqui escreve em disco.

Dois formatos, um dicionário de saída. Quem consome — o extrator de dossiê e a
triagem — não precisa saber de qual harness veio a sessão.

    ~/.claude/projects/<slug-do-cwd>/<sessionId>.jsonl        Claude Code
    ~/.codex/sessions/<ano>/<mes>/<dia>/rollout-<ts>-<id>.jsonl   Codex

A diferença que mais importa não é o nome das chaves, é **como se reconhece o
prompt da pessoa**:

- No Claude, registro `user` é duas coisas — prompt e resultado de ferramenta —, e o
  discriminador é a ausência de `toolUseResult`, mais uma lista de marcadores de
  maquinaria do cliente (ver MAQUINARIA).
- No Codex não há ambiguidade: `event_msg` com `payload.type == "user_message"` é o
  que a pessoa digitou, e nada mais é. Os `response_item` com `role: "user"` são
  injeção do harness (AGENTS.md, `<environment_context>`) e **não** entram.

Formatos conferidos em 652 rollouts do Codex (2025-09 a 2026-08) e 203 sessões do
Claude. O que variou no período, e por isso é lido com tolerância:

- `session_meta.payload` traz `id` sempre e `session_id` só nas versões novas.
- Ferramenta de shell é `exec_command` (argumento `cmd`, string), `shell` (argumento
  `command`, lista no estilo `["bash","-lc","…"]`) ou a ferramenta customizada `exec`,
  cujo `input` é um trecho de JavaScript chamando `tools.exec_command`.
- `function_call_output.output` é string na esmagadora maioria e **lista** quando a
  saída tem imagem. Nesse caso os blocos não-texto são descartados: são data URI de
  PNG em base64, e um deles sozinho enche o dossiê.
"""

import json
import os
import re
from glob import glob

RAIZ_CLAUDE = os.path.expanduser("~/.claude/projects")
RAIZ_CODEX = os.path.expanduser("~/.codex/sessions")

# Registros `user` do Claude que o cliente gera em nome da pessoa: eco de slash command,
# aviso de comando local, saída do comando e o sumário de compactação. Todos passam pelo
# teste do toolUseResult, e o sumário sozinho traz centenas de linhas. Marcadores medidos.
MAQUINARIA = (
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<system-reminder>",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
    # Corpo da skill injetado pela ferramenta Skill. Chega como registro `user` sem
    # `toolUseResult` e passa por todos os testes anteriores -- e é texto de skill, não
    # da pessoa. Medido: 20 em 60 transcripts, cada um com centenas de linhas. Contado
    # como prompt, ele domina qualquer estatística de vocabulário e faz a triagem
    # "descobrir" que o relator repete `references`, `template` e `build`, que são
    # palavras nossas.
    "Base directory for this skill:",
    # Aviso de tarefa em segundo plano concluída, gerado pelo harness.
    "<task-notification>",
    "<task-id>",
)

# Ferramentas do Codex que executam comando. `update_plan`, `spawn_agent` e afins ficam
# de fora de propósito: não são evidência de investigação, são orquestração.
FERRAMENTAS_SHELL = {"exec_command", "shell", "local_shell", "container.exec"}

_CMD_EM_JS = re.compile(r'"cmd"\s*:\s*"((?:[^"\\]|\\.)*)"')


def carregar(caminho):
    """Registros de um JSONL, pulando linha ilegível em vez de abortar."""
    with open(caminho, errors="ignore") as f:
        for linha in f:
            try:
                yield json.loads(linha)
            except json.JSONDecodeError:
                continue


def formato_de(caminho, olhar=8):
    """Qual harness — e qual geração dele — gravou este arquivo.

    Decidido pelos primeiros registros, não pelo caminho: assim um transcript copiado
    para outro lugar continua legível. `codex-antigo` é a terceira geração encontrada
    no disco: registros planos, sem `payload`, sem `session_meta` e **sem
    `user_message`** — nela o prompt da pessoa e a injeção de `<environment_context>`
    são os dois `{"type":"message","role":"user"}`, indistinguíveis sem heurística nova.
    São 5 arquivos de 652, todos de 2025-09. Reconhecer e recusar é mais honesto que
    parsear errado: lidos como Claude, eles saem com 0 prompts e sem título, o que
    parece sessão vazia em vez de formato não suportado.
    """
    for i, reg in enumerate(carregar(caminho)):
        if i >= olhar:
            break
        if reg.get("type") == "session_meta":
            return "codex"
        if reg.get("record_type") == "state":
            return "codex-antigo"
        if "instructions" in reg and "id" in reg and "type" not in reg:
            return "codex-antigo"
        if reg.get("type") in ("summary", "user", "assistant", "ai-title"):
            return "claude"
    return "claude"


# ---------------------------------------------------------------- Claude Code

def _texto_claude(conteudo):
    if isinstance(conteudo, str):
        return conteudo
    if isinstance(conteudo, list):
        partes = [b.get("text", "") for b in conteudo
                  if isinstance(b, dict) and b.get("type") == "text"]
        return "\n".join(p for p in partes if p)
    return ""


def eh_prompt_real(reg):
    """Prompt do relator, e não saída de ferramenta nem maquinaria do cliente."""
    if reg.get("type") != "user" or "toolUseResult" in reg:
        return False
    texto = _texto_claude(reg.get("message", {}).get("content", "")).lstrip()
    if any(m in texto[:600] for m in MAQUINARIA):
        return False
    return not (texto.startswith("/") and len(texto.split()) <= 3)


def _ler_claude(caminho):
    d = _vazio(caminho, "claude")
    pendentes = {}

    for reg in carregar(caminho):
        ts = reg.get("timestamp", "")
        if ts:
            d["inicio"] = d["inicio"] or ts
            d["fim"] = ts
        if reg.get("isSidechain"):
            d["filha"] = True

        t = reg.get("type")

        if t == "ai-title":
            d["titulo"] = d["titulo"] or reg.get("aiTitle")
            continue

        if t == "assistant":
            d["cwd"] = d["cwd"] or reg.get("cwd")
            d["branch"] = d["branch"] or reg.get("gitBranch")
            d["versao"] = d["versao"] or reg.get("version")
            for b in reg.get("message", {}).get("content", []) or []:
                if not isinstance(b, dict):
                    continue
                if b.get("type") == "thinking":
                    d["raciocinios"] += 1
                elif b.get("type") == "text" and b.get("text", "").strip():
                    d["conclusoes"].append((ts, b["text"].strip()))
                elif b.get("type") == "tool_use":
                    nome, entrada = b.get("name"), b.get("input", {}) or {}
                    if nome == "Bash":
                        pendentes[b.get("id")] = {
                            "ts": ts,
                            "cmd": entrada.get("command", ""),
                            "desc": entrada.get("description", ""),
                        }
                    elif nome in ("Write", "Edit", "NotebookEdit"):
                        d["arquivos"].append((nome, entrada.get("file_path", "")))
            continue

        if eh_prompt_real(reg):
            txt = _texto_claude(reg.get("message", {}).get("content"))
            if txt.strip():
                d["prompts"].append((ts, txt.strip()))
            continue

        if t == "user":
            tur = reg.get("toolUseResult")
            for b in reg.get("message", {}).get("content", []) or []:
                if not isinstance(b, dict) or b.get("type") != "tool_result":
                    continue
                cmd = pendentes.pop(b.get("tool_use_id"), None)
                if not cmd:
                    continue
                saida = tur.get("stdout", "") if isinstance(tur, dict) else ""
                stderr = tur.get("stderr", "") if isinstance(tur, dict) else ""
                cmd.update(erro=bool(b.get("is_error")), vazio=not saida.strip(),
                           stderr=stderr.strip()[:200])
                d["comandos"].append(cmd)

    d["id"] = os.path.basename(caminho)[:-6]
    return _fechar(d, pendentes)


# ---------------------------------------------------------------------- Codex

def _texto_codex(saida):
    """Texto de um `function_call_output`, descartando bloco de imagem.

    A lista aparece quando a ferramenta devolveu screenshot: são data URI de PNG em
    base64, com centenas de KB cada. Entram no dossiê como nada.
    """
    if isinstance(saida, str):
        return saida
    if isinstance(saida, list):
        return "\n".join(b.get("text", "") for b in saida
                         if isinstance(b, dict) and b.get("type") in ("text", "output_text"))
    return ""


def _comando_de(payload):
    """O comando de uma chamada de ferramenta do Codex, nas três formas que existem."""
    nome = payload.get("name")
    if nome in FERRAMENTAS_SHELL:
        try:
            args = json.loads(payload.get("arguments") or "{}")
        except (json.JSONDecodeError, TypeError):
            return payload.get("arguments", "")
        cmd = args.get("cmd") or args.get("command") or ""
        if isinstance(cmd, list):
            # `["bash","-lc","…"]` — o que interessa é o último elemento; os dois
            # primeiros são o invólucro e repeti-los em todo comando é ruído.
            cmd = cmd[-1] if cmd else ""
        return cmd
    if nome == "exec":
        # Ferramenta customizada: o `input` é JavaScript chamando `tools.exec_command`.
        m = _CMD_EM_JS.search(payload.get("input") or "")
        if m:
            try:
                return json.loads(f'"{m.group(1)}"')
            except json.JSONDecodeError:
                return m.group(1)
        return (payload.get("input") or "").strip()
    return ""


def _ler_codex(caminho):
    d = _vazio(caminho, "codex")
    pendentes = {}

    for reg in carregar(caminho):
        ts = reg.get("timestamp", "")
        if ts:
            d["inicio"] = d["inicio"] or ts
            d["fim"] = ts
        tipo = reg.get("type")
        p = reg.get("payload")
        if not isinstance(p, dict):
            continue
        sub = p.get("type")

        if tipo == "session_meta":
            d["id"] = p.get("session_id") or p.get("id") or d["id"]
            d["cwd"] = d["cwd"] or p.get("cwd")
            d["versao"] = d["versao"] or p.get("cli_version")
            git = p.get("git")
            if isinstance(git, dict):
                d["branch"] = d["branch"] or git.get("branch")
            # Sessão filha: o Codex a marca pelo vínculo com a thread que a criou.
            d["filha"] = d["filha"] or bool(p.get("parent_thread_id"))
            continue

        if tipo == "event_msg":
            if sub == "user_message":
                txt = (p.get("message") or "").strip()
                if txt:
                    d["prompts"].append((ts, txt))
            elif sub == "agent_message":
                txt = (p.get("message") or "").strip()
                if txt:
                    d["conclusoes"].append((ts, txt))
            elif sub == "agent_reasoning":
                d["raciocinios"] += 1
            elif sub == "patch_apply_end":
                # A fonte boa de arquivo tocado: traz o resultado, não a intenção.
                mudancas = p.get("changes")
                if isinstance(mudancas, dict) and p.get("success"):
                    for arq, info in mudancas.items():
                        acao = (info or {}).get("type", "update") if isinstance(info, dict) else "update"
                        d["arquivos"].append((f"apply_patch/{acao}", arq))
            continue

        if tipo != "response_item":
            continue

        if sub == "reasoning":
            d["raciocinios"] += 1
        elif sub in ("function_call", "custom_tool_call"):
            cmd = _comando_de(p)
            if cmd:
                pendentes[p.get("call_id")] = {"ts": ts, "cmd": cmd, "desc": ""}
        elif sub in ("function_call_output", "custom_tool_call_output"):
            reg_cmd = pendentes.pop(p.get("call_id"), None)
            if not reg_cmd:
                continue
            saida = _texto_codex(p.get("output"))
            m = re.search(r"Process exited with code (\d+)", saida)
            corpo = saida.split("\nOutput:\n", 1)[1] if "\nOutput:\n" in saida else saida
            reg_cmd.update(erro=bool(m) and m.group(1) != "0",
                           vazio=not corpo.strip(),
                           stderr=corpo.strip()[-200:] if m and m.group(1) != "0" else "")
            d["comandos"].append(reg_cmd)

    if not d["titulo"] and d["prompts"]:
        # O Codex não grava título. O primeiro prompt é o melhor rótulo disponível.
        d["titulo"] = d["prompts"][0][1].splitlines()[0][:58]
    return _fechar(d, pendentes)


# ------------------------------------------------------------------- comum

def _vazio(caminho, formato):
    return {
        "caminho": caminho, "formato": formato, "id": os.path.basename(caminho),
        "titulo": None, "cwd": None, "branch": None, "versao": None,
        "inicio": None, "fim": None, "filha": False, "raciocinios": 0,
        "prompts": [], "comandos": [], "conclusoes": [], "arquivos": [],
    }


def _fechar(d, pendentes):
    for restante in pendentes.values():   # chamada sem resultado casado
        restante.update(erro=False, vazio=False, stderr="")
        d["comandos"].append(restante)
    d["comandos"].sort(key=lambda c: c["ts"])
    return d


class FormatoNaoSuportado(Exception):
    """Transcript de geração que este leitor não parseia. Ver `formato_de`."""


def ler(caminho):
    """Sessão normalizada, qualquer que seja o harness que a gravou."""
    fmt = formato_de(caminho)
    if fmt == "codex-antigo":
        raise FormatoNaoSuportado(
            f"{caminho}: rollout do Codex no formato plano de 2025-09, sem `user_message` "
            "— o prompt da pessoa não é separável da injeção do harness")
    return _ler_codex(caminho) if fmt == "codex" else _ler_claude(caminho)


def transcripts(formato=None, filhas=False):
    """Todo transcript local, mais recente primeiro pelo mtime do arquivo.

    Sessão de subagente fica **de fora por padrão**. Ela não é conversa com pessoa: não
    tem prompt do relator, e contá-la infla a amostra com material que não rende skill.
    No Claude são 116 dos 204 arquivos, em `<sessão>/subagents/agent-*.jsonl`; no Codex
    elas se identificam pelo `parent_thread_id` e só dá para saber lendo — por isso o
    filtro por caminho aqui, e o campo `filha` de quem lê.
    """
    achados = []
    if formato in (None, "claude"):
        achados += glob(os.path.join(RAIZ_CLAUDE, "**", "*.jsonl"), recursive=True)
    if formato in (None, "codex"):
        achados += glob(os.path.join(RAIZ_CODEX, "**", "rollout-*.jsonl"), recursive=True)
    if not filhas:
        achados = [a for a in achados if f"{os.sep}subagents{os.sep}" not in a]
    return sorted(achados, key=lambda a: os.path.getmtime(a), reverse=True)


def resumo(caminho):
    """Só o suficiente para listar: rótulo, diretório, data e contagem de prompts.

    Existe porque `ler()` percorre o arquivo inteiro, e listar 740 transcripts assim
    custa minutos. Aqui a leitura do Codex para assim que tem `session_meta` e o
    primeiro `user_message` — o resto do arquivo não muda o rótulo.
    """
    fmt = formato_de(caminho)
    titulo = cwd = quando = None
    prompts = 0

    if fmt == "codex-antigo":
        titulo = "(formato antigo do Codex — não suportado)"
    elif fmt == "codex":
        for reg in carregar(caminho):
            p = reg.get("payload")
            if not isinstance(p, dict):
                continue
            if reg.get("type") == "session_meta":
                cwd = cwd or p.get("cwd")
                quando = quando or (reg.get("timestamp") or "")[:10]
            elif p.get("type") == "user_message":
                prompts += 1
                if not titulo:
                    titulo = (p.get("message") or "").strip().splitlines()[0][:58]
    else:
        for reg in carregar(caminho):
            t = reg.get("type")
            if t == "ai-title" and not titulo:
                titulo = reg.get("aiTitle")
            elif t == "assistant":
                cwd = cwd or reg.get("cwd")
                quando = quando or reg.get("timestamp", "")[:10]
            elif eh_prompt_real(reg):
                prompts += 1

    return {"caminho": caminho, "formato": fmt, "titulo": titulo,
            "cwd": cwd, "quando": quando, "prompts": prompts}


def resolver(alvo):
    """Caminho, sessionId, ou pedaço de sessionId."""
    if os.path.isfile(alvo):
        return alvo
    for caminho in transcripts():
        if alvo in os.path.basename(caminho):
            return caminho
    return None
